### ISSUE TITLE
undefined name 'epoch_iterator' in jaqket_baseline.py

### ISSUE THREAD

**Issue by upura** [cl-tohoku/JAQKET_baseline#2]
There is a statement `epoch_iterator.close()` in L609 of `jaqket_baseline.py`, but `epoch_iterator` hasn't been defined before.
https://github.com/cl-tohoku/JAQKET_baseline/blob/master/jaqket_baseline.py#L609

**Comment by katotakuma0501** [comment]
I'm sorry for the late reply. As kumapo says, please change epoch_iterator.close to train_iterator.close.
